export const JB = [
    {
        "name": "Layer7",
        "description": "해킹 전문 동아리",
        "url": "http://layer7.kr/",
        "location": "3호관 334실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIS%2FLAYER7.png?alt=media&token=6014d886-ec29-4f2e-9019-0cd84716d87d",
        "facebook": "https://www.facebook.com/letsgolayer7/",
        "instagram": "",
        "leader": "김태영",
        "viceleader": "김나희",
        "leader_sns": "",
        "vleader_sns": "https://www.instagram.com/rin21.17",
        "department": 0,
        "type": 0,
        "curriculum": ""
    },
    {
        "name": "Unifox",
        "description": "정보보호과 프로그래밍 동아리",
        "url": "http://unifox.kr",
        "location": "3호관 332실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIS%2FUNIFOX.png?alt=media&token=1994bf8f-cc41-43d8-bc1a-41d03c57a0ce",
        "facebook": "https://www.facebook.com/UnifoxToTheWorld/?ref=m_notif&notif_t=page_post_reaction",
        "instagram": "",
        "leader": "양윤혁",
        "viceleader": "유창하",
        "leader_sns": "",
        "vleader_sns": "",
        "department": 0,
        "type": 0,
        "curriculum": "c언어|알고리즘|시큐어코딩"
    },
    {
        "name": "Emotion",
        "description": "이모션은 선린인터넷고등학교 정보보호과 전공동아리로 인공지능에 관심을 가진 학생들이 모여 구성된 인공지능 개발 동아리입니다 :) 저희는 인공지능 개발에 기본이 되는 프로그래밍 언어 파이썬을 배우고, 파이썬을 이용한 데이터 분석과 인공지능의 기초적인 부분과 인공지능에서 꼭 알아야 하는 중요 개념들을 위주로 수업을 진행합니다. 또한 다양한 프로젝트를 진행함으로써 자신의 프로그래밍 실력과 인공지능 개발 실력을 향상시키는 동아리입니다.",
        "url": "http://ernotion.kr/",
        "location": "4호관 411실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIS%2FEMOTION.jpg?alt=media&token=d1401bd6-0c5f-4225-bc51-4c0fcf264f84",
        "facebook": "https://www.facebook.com/sunrinemotion/",
        "instagram": "https://www.instagram.com/sunrin_emotion._.00",
        "leader": "김태현",
        "viceleader": "박주형",
        "leader_sns": "",
        "vleader_sns": "https://www.instagram.com/juhyeongpark1",
        "department": 0,
        "type": 0,
        "curriculum": "Python|데이터 분석|머신러닝|딥러닝|인공지능 윤리"
    },
    {
        "name": "NEFUS",
        "description": "IoT&Network 전공동아리",
        "url": "http://nefus.kr/",
        "location": "3호관 331실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIS%2FNEFUS.jpg?alt=media&token=d0af2638-43e9-43a0-926f-6fffc5ed8bb2",
        "facebook": "https://www.facebook.com/sunrinefus/",
        "instagram": "",
        "leader": "인지해",
        "viceleader": "박인서",
        "leader_sns": "https://www.instagram.com/recog_nize_05",
        "vleader_sns": "",
        "department": 0,
        "type": 0,
        "curriculum": "C언어|아두이노|파이썬|웹|라즈베리파이|네트워크|프로젝트"
    },
    {
        "name": "TeamLog",
        "description": "안녕 나를 소개하지 이름 팀로그 직업은 서버 프로그래밍 취미는 WEB, NETWORK, SERVER 원해? 이 모든 걸 하나로 아울러 주는 답 난 커다란 여정의 시작 앞에 서 있어 따라와 줘 원한다면 -2022 팀로그-",
        "url": "http://teamlog.kr/",
        "location": "정보없음",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIS%2FTEAMLOG.jpg?alt=media&token=9eefdd94-a41d-47bd-81a3-2b6c440b529f",
        "facebook": "https://www.facebook.com/sunrintog/",
        "instagram": "",
        "leader": "양승찬",
        "viceleader": "박건우",
        "leader_sns": "https://www.instagram.com/yangseungchan3",
        "vleader_sns": "https://www.instagram.com/gun_u.922",
        "department": 0,
        "type": 0,
        "curriculum": ""
    }
]

export const SW = [
    {
        "name": "RG",
        "description": "반갑습니다! 저희는 선린 게임개발 동아리 RG입니다. RG는 선후배간 수평적인 분위기를 지향하여 모두가 즐거운 분위기 안에서 동아리 활동을 진행합니다. 개발 팀에서는 C와 C++등의 언어에 대한 기초 지식을 배우고, 유니티 엔진을 통해 2D/3D 게임을 직접 만들어 볼 뿐 아니라 게임 기획 및 구조론까지도 배울 수 있습니다. 한편 디자인 팀에서는 2D드로잉과 픽셀아트 그래픽부터 3D툴을 이용한 모델링 작업 등을 진행합니다.",
        "url": "https://sunrin-rg.github.io/",
        "location": "3호관 351실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FRG.jpg?alt=media&token=da7a275e-1abf-4890-aad6-e93186cbe3bc",
        "facebook": "https://www.facebook.com/sunrintrg",
        "instagram": "https://www.instagram.com/republic_of_game_rg/",
        "leader": "이진우",
        "viceleader": "김대희",
        "leader_sns": "https://www.facebook.com/profile.php?id=100015153185928",
        "vleader_sns": "https://www.facebook.com/profile.php?id=100015510971253",
        "department": 1,
        "type": 0,
        "curriculum": ""
    },
    {
        "name": "ZER0PEN",
        "description": "소프트웨어과 게임 개발 전문동아리 제로픈입니다. 제로픈은 자유로운 분위기를 지향하는 동시에 동아리내 활동 또한 자유로운 편입니다. 소프트웨어과와 콘텐츠디자인과 학생들이 어울려 게임을 만들어보고 서로 피드백하는 것이 주요 활동 중 하나입니다.  소프트웨어과 (개발자) - C, C#, C++같은 프로그래밍언어의 전반적인 지식을 배우고, 유니티를 사용한 게임 개발 및 게임을 기획하는 부분 등 게임 개발에 있어서 필요한 것들의 수업을 진행합니다. 콘텐츠디자인과",
        "url": "https://zer0pen.kr/",
        "location": "3호관 343실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FZEROPEN.jpg?alt=media&token=dfdc4c59-eb05-4dd7-8024-7079d05b607d",
        "facebook": "https://www.facebook.com/zer0pen/",
        "instagram": "https://www.instagram.com/zer0pen_/",
        "leader": "이제윤",
        "viceleader": "차하람",
        "leader_sns": "https://www.instagram.com/jeyoun_00",
        "vleader_sns": "https://www.instagram.com/print_1814",
        "department": 1,
        "type": 0,
        "curriculum": "유니티|제로엔진|게임기획|C++|C#|포토샵|픽셀아트|캐릭터 디자인|게임 이펙트|UI/UX 디자인"
    },
    {
        "name": "App:ple Pi",
        "description": "선린 최초의 앱 개발 창업 동아리 App:ple Pi는 안드로이드 앱 개발과 UI/UX 디자인을 중점으로 매년 꾸준한 실적을 내고있습니다. 화목하고 즐거운 분위기와 체계적인 커리큘럼으로 인해 선후배간의 교류가 높은 편으로, 신입생이더라도 교내외에서 다양한 경험을 쌓을 수 있는 동아리입니다. 또한 신설된 4호관에 우수한 동아리실을 보유하고 있어 자유롭고 우수한 환경을 제공하고있습니다. 모바일의 혁신을 향하여, App:ple Pi",
        "url": "https://appplepi.com/",
        "location": "4호관422실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FAPPLEPI.jpg?alt=media&token=e02e1025-2d98-4e4b-88ab-8e6f204bd3e2",
        "facebook": "https://www.facebook.com/app.plepi/",
        "instagram": "https://www.instagram.com/appple.pi.official",
        "leader": "김병주",
        "viceleader": "이지현",
        "leader_sns": "https://www.instagram.com/byungju5315",
        "vleader_sns": " https://www.instagram.com/ji.hyun__0",
        "department": 1,
        "type": 0,
        "curriculum": "Androis Studio|Git|Adobe Xd"
    },
    {
        "name": "IWOP",
        "description": "선린인터넷고등학교의 대표 웹 동아리 IWOP 입니다. 2001년을 시작으로 2022학년도 기준 24기 모집 중입니다. 웹개발의 전반적인 지식을 배울 수 있으며, 우수한 실적과 커리큘럼을 보유하고 있습니다. ",
        "url": "https://iwop.github.io",
        "location": "3호관 342실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FIWOP.png?alt=media&token=ae9973f7-09d2-4d5b-9a1a-7b092398c66c",
        "facebook": "https://www.facebook.com/sunrinIwop",
        "instagram": "https://www.instagram.com/iwop_sunrin",
        "leader": "나제원",
        "viceleader": "윤도현",
        "leader_sns": "https://www.facebook.com/profile.php?id=100027480555895 ",
        "vleader_sns": "",
        "department": 1,
        "type": 0,
        "curriculum": "HTML|CSS|JS|TS|node.js|vue.js|react|svelte|webpack|github"
    },
    {
        "name": "AnA",
        "description": "Node JS, 데이터베이스, 리눅스를 같이 학습하며, 전체적인 백엔드 개발을 배우는 동아리 입니다. 부가적으로 AWS와 git 수업을 진행하고 있습니다.",
        "url": "http://www.sunrin-ana.kr/",
        "location": "4호관 423실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FANA.png?alt=media&token=40fa293e-c161-4f94-97d9-ca08c7bd9e7c",
        "facebook": "https://www.facebook.com/sunrinana",
        "instagram": "",
        "leader": "김형진",
        "viceleader": "김승태",
        "leader_sns": "",
        "vleader_sns": "",
        "department": 1,
        "type": 0,
        "curriculum": "HTML|CSS|JS|NodeJS|MySQL|AWS|Linux"
    },
    {
        "name": "EDCAN",
        "description": "새로운 모바일 콘텐츠 시대를 이끌어가는 크리에이터들의 동아리 EDCAN입니다.저희 EDCAN은 모바일 콘텐츠 개발반으로 안드로이드 앱, 웹 등 다양한 개발과 디자인을 공부합니다.저희 EDCAN은 남들이 같은것을 만들때 우리만의 것을 만드는 크리에이터들입니다.",
        "url": "https://edcan.kr",
        "location": "4호관 421실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FSW%2FEDCAN.jpg?alt=media&token=f4573e5f-a7fe-4914-a479-38307f88feec",
        "facebook": "https://www.facebook.com/edcancircle",
        "instagram": "https://www.instagram.com/sunrin_edcan",
        "leader": "진다은",
        "viceleader": "박희찬",
        "leader_sns": "https://www.instagram.com/hwlsek21",
        "vleader_sns": "https://www.instagram.com/ckstmznf",
        "department": 1,
        "type": 0,
        "curriculum": "Kotlin|Android Studio|JavaScript|Vue.js|Node.js|Figma|XD|앱 UI/UX|웹 UI/UX"
    }
]

export const it = [
    {
        "name": "HMH",
        "description": "IT경영과 동아리중 유일한 IT동아리 입니다. IT와 경영 경제를 접목하여 연구하고 있습니다.",
        "url": "",
        "location": "4호관 423실 ",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIM%2FHMH.png?alt=media&token=d80ccb4e-f4df-4d0c-9d1a-51432d3167eb",
        "facebook": "",
        "instagram": "",
        "leader": "정인서",
        "viceleader": "이찬",
        "leader_sns": "https://www.instagram.com/dlsseo",
        "vleader_sns": "https://www.instagram.com/1210_chan",
        "department": 2,
        "type": 0,
        "curriculum": "빅데이터 분석 및 활용|R언어|쇼핑몰구축 "
    },
    {
        "name": "BFD",
        "description": "BFD는 “Business Foundation Dream”의 약자로 ‘창업 기반의 꿈’을 의미합니다. 창업에 대해서 배우고 간접적으로 느낄 수 있는 동아리입니다.",
        "url": "",
        "location": "1호관 3층 12실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIM%2FBFD.jpg?alt=media&token=50d0e1c8-617b-4869-9ed0-838bc6857078",
        "facebook": "",
        "instagram": "https://www.instagram.com/sunrin_bfd",
        "leader": "손지원",
        "viceleader": "이민규",
        "leader_sns": "https://www.instagram.com/under_thxxea",
        "vleader_sns": "https://www.instagram.com/mingyu_9495",
        "department": 2,
        "type": 0,
        "curriculum": "창업의 기초, 성공비법, 경영 전략, 비즈쿨 등을 배우며 직접 해 봄"
    },
    {
        "name": "FRS",
        "description": "FRS는 IT경영과 유일한 전문 금융 연구동아리이며 펀드,주식,채권에 관련된 금융과 경제를 연구하고 분석하는 동아리 입니다.",
        "url": "",
        "location": "정보없음",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIM%2FFRS.jpg?alt=media&token=233cf388-ba44-460d-a12c-38cd0c629cd7",
        "facebook": "",
        "instagram": "https://www.instagram.com/sunrin_frs",
        "leader": "최용준",
        "viceleader": "박선우",
        "leader_sns": "https://www.instagram.com/18_yongjun",
        "vleader_sns": "https://www.instagram.com/05_s_w",
        "department": 2,
        "type": 0,
        "curriculum": ""
    },
    {
        "name": "KIWI",
        "description": "키위 노믹스는 경제학적으로 사회의 여러 이슈와 사건들을 보고 연구하는 경영 경제 연구동아리입니다.",
        "url": "",
        "location": "정보없음",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FIM%2FKIWI.jpg?alt=media&token=4c75561c-8839-494b-accc-41891e0e0730",
        "facebook": "",
        "instagram": "",
        "leader": "김재혁",
        "viceleader": "정우석",
        "leader_sns": "https://www.instagram.com/hyuk_0102",
        "vleader_sns": "https://www.instagram.com/wooseok0123",
        "department": 2,
        "type": 0,
        "curriculum": ""
    }
]

export const de = [
    {
        "name": "TATE",
        "description": "저희는 선린인터넷고등학교의 콘텐츠디자인과 디자인 전문 연구 동아리 TATE입니다! TATE에서는 포토샵, 일러스트, 3D MAX 등을 이용해 수업을 진행하여 여러 작업물을 스스로 만들어보며 여러 디자인 분야의 능력을 발전시킴과 동시에 창의력을 향상 시킬 수 있습니다. 또한 굿즈 제작 활동으로 학생들이 직접 구상제작한 창작물을 실사화 시킬 수 있습니다.",
        "url": "https://sunrintateweb.web.app/",
        "location": "3호관 322실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FCD%2FTATE.jpg?alt=media&token=ecd97729-fd4e-4f28-8c47-af9b187294aa",
        "facebook": "https://www.facebook.com/TATEDesignResearchClub",
        "instagram": "https://www.instagram.com/tate__official",
        "leader": "김정은",
        "viceleader": "문정윤",
        "leader_sns": "https://www.instagram.com/05_wjddms",
        "vleader_sns": "https://www.instagram.com/overthemoon_3301",
        "department": 3,
        "type": 0,
        "curriculum": "포토샵|일러스트레이터|손그림|3D|굿즈 작업"
    },
    {
        "name": "브이프렌즈(v.friends)",
        "description": "선린인터넷고등학교 콘텐츠디자인과의 교육 봉사 동아리이다.",
        "url": "https://vfriends.github.io/",
        "location": "4호관 431실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FCD%2FV.FRIENDS.jpg?alt=media&token=bfc1e081-6d9e-4bf8-a9dc-c96ef1d89f6f",
        "facebook": "https://www.facebook.com/with.v.friends",
        "instagram": "https://www.instagram.com/v.friends_official/",
        "leader": "이수빈",
        "viceleader": "권현진",
        "leader_sns": "https://www.instagram.com/_s_binese/",
        "vleader_sns": "https://www.instagram.com/hyeonjin.qo_op/",
        "department": 3,
        "type": 0,
        "curriculum": "UI/UX|그래픽 디자인|영상|3D"
    },
    {
        "name": "자의누리",
        "description": "교내최대 영상제작동아리, 세상의중심 자의누리입니다.",
        "url": "",
        "location": "3호관 352실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FCD%2F%E1%84%8C%E1%85%A1%E1%84%8B%E1%85%B4%E1%84%82%E1%85%AE%E1%84%85%E1%85%B5.jpg?alt=media&token=4b548eed-65d4-4e85-bae9-8fc111329b2b",
        "facebook": "https://www.facebook.com/centerworld",
        "instagram": "https://www.instagram.com/junr_official/",
        "leader": "채빛나",
        "viceleader": "신동민",
        "leader_sns": "https://www.instagram.com/twinkle._.me",
        "vleader_sns": "https://www.instagram.com/sinlio_124",
        "department": 3,
        "type": 0,
        "curriculum": "프리미어|애프터 이펙트"
    },
    {
        "name": "미르(MIR)",
        "description": "교내 유일 만화 • 일러스트레이션 전문 동아리 입니다.크로키, 해부학, 디지털 드로잉 수업을 통해 일러스트 실력을 키워갑니다.",
        "url": "",
        "location": "3호관 323실",
        "logo_url": "https://firebasestorage.googleapis.com/v0/b/sunrinlife-intranet.appspot.com/o/club-logo%2FCD%2FMIR.jpg?alt=media&token=6acfb03d-6aca-4a48-b943-d264f80c229c",
        "facebook": "https://url.kr/2coerw",
        "instagram": "https://www.instagram.com/mir.__.official",
        "leader": "이태은",
        "viceleader": "이시연",
        "leader_sns": "https://www.instagram.com/itaeeun673",
        "vleader_sns": "https://www.instagram.com/shawn_lee_7",
        "department": 3,
        "type": 0,
        "curriculum": "기초 드로잉|캐릭터 디자인|애니메이션 제작|배경 작화, 색감|일러스트 제작"
    }
]

// export { JB, SW, it, de };